import React from 'react'
import '../app/globals.css'
import { Inter } from 'next/font/google'
import { AnimatePresence, motion } from 'framer-motion';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout = ({children}) => {
  return (
    <motion.div
      initial={{ y: 100,z:0, opacity: 0 }}
      animate={{ y: 0,z:0, opacity: 1 }}
      exit={{ y: 300,z:100, opacity: 0 }}
      transition={{
        type: "spring",
        stiffness: 260,
        damping: 20,
      }}
    >
      {children}
    </motion.div>
  )
}

export default Layout;
